let IMG={hotpot:'https://images.unsplash.com/photo-1708597523963-40b30f846281?auto=format&fit=crop&w=900&q=80',sushi:'https://images.unsplash.com/photo-1661697216102-370e429f849f?auto=format&fit=crop&w=900&q=80',sichuan:'https://images.unsplash.com/photo-1708597523963-40b30f846281?auto=format&fit=crop&w=900&q=80',korean:'https://images.unsplash.com/photo-1550388341-d3d5ac2a724e?auto=format&fit=crop&w=900&q=80',bbq:'https://images.unsplash.com/photo-1550388341-d3d5ac2a724e?auto=format&fit=crop&w=900&q=80',western:'https://images.unsplash.com/photo-1661697216102-370e429f849f?auto=format&fit=crop&w=900&q=80'};
async function loadAssets(){const t=await fetch('assets/boy.b64').then(r=>r.text());const boy='data:image/webp;base64,'+t.trim();IMG.boy=boy;IMG.avatar=boy;document.querySelectorAll('[data-img]').forEach(el=>el.src=IMG[el.dataset.img]);}
const DATA=[
{name:'川湘菜',emoji:'🌶️',img:IMG.sichuan,subs:['川菜','湘菜','江西小炒','酸菜鱼','烤鱼','干锅'],tags:['辣','聚餐']},
{name:'火锅',emoji:'🍲',img:IMG.hotpot,subs:['重庆火锅','四川火锅','潮汕牛肉火锅','北京铜锅涮肉','椰子鸡','菌子火锅'],tags:['辣','聚餐','累']},
{name:'烧烤',emoji:'🍖',img:IMG.bbq,subs:['东北烧烤','新疆烧烤','烤羊肉串','韩式烤肉','夜宵烧烤'],tags:['聚餐','累']},
{name:'日料',emoji:'🍣',img:IMG.sushi,subs:['寿司','日式拉面','烧鸟','寿喜烧','日式烤肉','鳗鱼饭'],tags:['清淡','吃好']},
{name:'韩餐',emoji:'🥘',img:IMG.korean,subs:['韩式烤肉','部队锅','石锅拌饭','冷面','炸鸡'],tags:['聚餐','吃好']},
{name:'西餐',emoji:'🍝',img:IMG.western,subs:['意大利面','披萨','牛排','焗饭','Brunch'],tags:['吃好','清淡']},
{name:'面 / 粉',emoji:'🍜',img:IMG.korean,subs:['兰州牛肉面','重庆小面','刀削面','油泼面','云南米线','螺蛳粉'],tags:['省钱','累']},
{name:'米饭套餐',emoji:'🍛',img:IMG.korean,subs:['盖饭','黄焖鸡','煲仔饭','卤肉饭','咖喱饭'],tags:['省钱','累']},
{name:'西北菜',emoji:'🫓',img:IMG.bbq,subs:['新疆菜','大盘鸡','手抓饭','羊肉泡馍'],tags:['聚餐','省钱']},
{name:'东南亚菜',emoji:'🥭',img:IMG.sushi,subs:['泰国菜','越南河粉','冬阴功','海南鸡饭'],tags:['清淡','吃好']},
{name:'小吃',emoji:'🥟',img:IMG.sichuan,subs:['麻辣烫','冒菜','生煎','锅贴','肉夹馍'],tags:['省钱','累']},
{name:'汉堡快餐',emoji:'🍔',img:IMG.western,subs:['汉堡','炸鸡','三明治','热狗'],tags:['省钱','累']},
{name:'轻食',emoji:'🥗',img:IMG.western,subs:['沙拉','Poke','低脂餐','健身餐'],tags:['清淡']},
{name:'家常菜',emoji:'🍚',img:IMG.sichuan,subs:['北京菜','东北菜','粤菜','江浙菜','家常小炒'],tags:['清淡','省钱']},
{name:'Brunch',emoji:'☕',img:IMG.western,subs:['贝果','三明治','松饼','可颂','咖啡简餐'],tags:['清淡','吃好']},
{name:'甜品',emoji:'🍰',img:IMG.sushi,subs:['奶茶','果茶','冰淇淋','蛋糕','糖水'],tags:['吃好']}
];
const MOODS=[['random','🥹','随便吃点'],['辣','🌶️','想吃辣'],['清淡','🌿','清淡一点'],['省钱','💰','省点钱'],['吃好','✨','吃好一点'],['累','😩','好累啊'],['聚餐','👯','和朋友'],['walk','🚶','不想走远']];
let mood=new Set(['random']),current=DATA[3],sub='寿喜烧',rolls=0,files=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function renderMoods(){const box=$('#moods');box.innerHTML='';MOODS.forEach(([id,e,l])=>{const b=document.createElement('button');b.className='mood'+(mood.has(id)?' active':'');b.innerHTML=`<b>${e}</b><span>${l}</span>`;b.onclick=()=>{if(id==='random')mood=new Set(['random']);else{mood.delete('random');mood.has(id)?mood.delete(id):mood.add(id);if(!mood.size)mood.add('random')}renderMoods()};box.appendChild(b)})}
function renderCats(){const box=$('#categories');box.innerHTML='';DATA.forEach((c,i)=>{const b=document.createElement('button');b.className='cat'+(c===current?' active':'');b.innerHTML=`<b>${c.emoji}</b><span>${c.name}</span>`;b.onclick=()=>{current=c;sub=c.subs[0];updateResult();renderCats();window.scrollTo({top:0,behavior:'smooth'})};box.appendChild(b)})}
function renderPopular(){const p=[DATA[1],DATA[3],DATA[0],DATA[4],DATA[2],DATA[5]].sort(()=>Math.random()-.5);$('#popularGrid').innerHTML=p.map(c=>`<button class="food-tile" data-name="${c.name}"><img src="${c.img}"><span>${c.emoji} ${c.name}</span></button>`).join('');$$('.food-tile').forEach(b=>b.onclick=()=>{current=DATA.find(x=>x.name===b.dataset.name);sub=current.subs[0];updateResult();renderCats()})}
function pool(){const ms=[...mood].filter(x=>x!=='random'&&x!=='walk');const p=ms.length?DATA.filter(c=>ms.some(m=>c.tags.includes(m))):DATA;return p.length?p:DATA}
function roll(){const d=$('#dice');d.classList.add('spin');d.textContent=['⚀','⚁','⚂','⚃','⚄','⚅'][Math.floor(Math.random()*6)];setTimeout(()=>{current=pool()[Math.floor(Math.random()*pool().length)];sub=current.subs[Math.floor(Math.random()*current.subs.length)];rolls++;d.classList.remove('spin');d.textContent=current.emoji;updateResult();renderCats();if(rolls>=4)toast(`已经第 ${rolls} 次了……你是不是心里其实有答案了？`)},560)}
function updateResult(){const title=`${current.name} · ${sub}`;$('#resultImg').src=current.img;$('#resultName').textContent=title;$('#resultDesc').textContent= current.name==='火锅'?'热乎乎的一顿，今天就别克制幸福感啦～':`今天就吃 ${sub}，这次不许再纠结了。`;$('#featureImg').src=current.img;$('#featureTitle').textContent=title;$('#featureDesc').textContent=`摇到了「${title}」。如果没有强烈反对，就把它当作今天的小命运，认真去吃一顿。`;$('#recInput').value=title;$('#actualInput').value=sub;renderRestaurants()}
function renderRestaurants(){const names={日料:['温野菜日式涮涮锅','牛角日本烧肉','将太无二'],火锅:['海底捞火锅','巴奴毛肚火锅','湊湊火锅'],川湘菜:['费大厨辣椒炒肉','川成元麻辣香锅','眉州东坡'],烧烤:['木屋烧烤','很久以前羊肉串','丰茂烤串']}[current.name]||['中关村精选餐厅 A','中关村精选餐厅 B','中关村精选餐厅 C'];const imgs=[current.img,IMG.hotpot,IMG.bbq];$('#restaurantList').innerHTML=names.map((n,i)=>`<div class="restaurant"><img src="${imgs[i]}"><div><b>${n}</b><small><span class="rating">★ ${(4.5+i*.1).toFixed(1)}</span> · 人均 ¥${98+i*35} · ${(.6+i*.3).toFixed(1)}km</small></div><button class="fav">♡</button></div>`).join('')}
function openModal(){$('#modal').classList.add('open')}function closeModal(){$('#modal').classList.remove('open')}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>x.classList.remove('show'),1900)}
$('#rollBtn').onclick=roll;$('#rerollBtn').onclick=roll;$('#subBtn').onclick=()=>{sub=current.subs[Math.floor(Math.random()*current.subs.length)];updateResult()};$('#acceptBtn').onclick=openModal;$('#checkinQuick').onclick=openModal;$('#openCheckin').onclick=openModal;$('#featureGo').onclick=openModal;$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};$('#shufflePopular').onclick=renderPopular;
$$('.nav button').forEach(b=>b.onclick=()=>{const el=document.getElementById(b.dataset.target);el?.scrollIntoView({behavior:'smooth',block:'start'});$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
$('#photoBtn').onclick=()=>$('#photoInput').click();$('#photoInput').onchange=e=>{files=[...e.target.files].slice(0,6);$('#previewRow').innerHTML='';files.forEach(f=>{const im=document.createElement('img');im.src=URL.createObjectURL(f);$('#previewRow').appendChild(im)})};
function getItems(){try{return JSON.parse(localStorage.getItem('eatCheckinsV2')||'[]')}catch{return []}}
function setItems(x){localStorage.setItem('eatCheckinsV2',JSON.stringify(x))}
async function fileToData(f){return await new Promise(res=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas'),max=700,s=Math.min(1,max/Math.max(im.width,im.height));c.width=im.width*s;c.height=im.height*s;c.getContext('2d').drawImage(im,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.72))};im.src=r.result};r.readAsDataURL(f)})}
async function save(full=true){const actual=full?$('#actualInput').value.trim():$('#quickActual').value.trim();if(!actual)return toast('先告诉我实际吃了什么～');const photo=files[0]?await fileToData(files[0]):current.img;const item={id:Date.now(),date:new Date().toISOString(),rec:full?$('#recInput').value:`${current.name} · ${sub}`,actual,restaurant:full?$('#restaurantInput').value:$('#quickRestaurant').value,price:full?Number($('#priceInput').value)||0:0,comment:full?$('#commentInput').value:'',photo};const arr=getItems();arr.unshift(item);setItems(arr.slice(0,50));closeModal();toast('打卡保存成功 ✨');renderStats();renderHistory()}
$('#saveCheckin').onclick=()=>save(true);$('#quickSave').onclick=()=>save(false);
function renderStats(){const a=getItems();$('#statCount').textContent=a.length;$('#statFav').textContent=Math.min(a.length,Math.round(a.length*.56));const now=new Date(),m=a.filter(x=>{const d=new Date(x.date);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}).length;$('#statMonth').textContent=m;const p=a.filter(x=>x.price);$('#statAvg').textContent=p.length?'¥'+Math.round(p.reduce((s,x)=>s+x.price,0)/p.length):'—'}
function renderHistory(){const a=getItems();const g=$('#historyGrid');if(!a.length){g.innerHTML=[[IMG.hotpot,'海底捞火锅'],[IMG.sushi,'寿喜烧'],[IMG.korean,'一兰拉面']].map(([im,n])=>`<div class="hist"><img src="${im}"><span>${n} · 示例</span></div>`).join('');return}g.innerHTML=a.slice(0,6).map(x=>`<div class="hist"><img src="${x.photo}"><span>${x.actual}${x.restaurant?' · '+x.restaurant:''}</span></div>`).join('')}
(async()=>{await loadAssets();renderMoods();renderCats();renderPopular();updateResult();renderStats();renderHistory();})();