const CATS=[
{name:'川湘菜',e:'🌶️',sub:['川菜','湘菜','酸菜鱼','烤鱼','干锅','江西小炒'],tags:['spicy','friends','treat']},
{name:'火锅',e:'🍲',sub:['重庆火锅','四川火锅','北京铜锅涮肉','潮汕牛肉火锅','椰子鸡','菌子火锅'],tags:['spicy','friends','treat','tired']},
{name:'烧烤',e:'🍖',sub:['东北烧烤','新疆烧烤','烤羊肉串','烤肉','夜宵烧烤'],tags:['friends','treat','tired']},
{name:'日料',e:'🍣',sub:['寿司','日式拉面','烧鸟','寿喜烧','日式烤肉','鳗鱼饭'],tags:['light','treat','friends']},
{name:'韩餐',e:'🥘',sub:['韩式烤肉','部队锅','石锅拌饭','冷面','炸鸡','韩式汤饭'],tags:['friends','treat','tired']},
{name:'西餐',e:'🍝',sub:['意大利面','披萨','牛排','焗饭','西式简餐','Brunch'],tags:['treat','friends','light']},
{name:'面 / 粉',e:'🍜',sub:['兰州牛肉面','重庆小面','刀削面','油泼面','云南米线','螺蛳粉'],tags:['budget','tired','spicy','near']},
{name:'米饭套餐',e:'🍛',sub:['盖饭','黄焖鸡','煲仔饭','卤肉饭','咖喱饭','肥牛饭'],tags:['budget','tired','near']},
{name:'西北菜',e:'🫓',sub:['新疆菜','大盘鸡','手抓饭','烤包子','羊肉泡馍'],tags:['friends','treat','budget']},
{name:'东南亚菜',e:'🥭',sub:['泰国菜','越南河粉','冬阴功','海南鸡饭','新加坡菜'],tags:['light','treat']},
{name:'小吃',e:'🥟',sub:['麻辣烫','冒菜','生煎','锅贴','肉夹馍','煎饼'],tags:['budget','near','tired','spicy']},
{name:'汉堡快餐',e:'🍔',sub:['汉堡','炸鸡','三明治','热狗','中式快餐'],tags:['budget','near','tired']},
{name:'轻食',e:'🥗',sub:['沙拉','Poke','低脂餐','健身餐','三明治','酸奶碗'],tags:['light','near']},
{name:'家常菜',e:'🍚',sub:['北京菜','东北菜','鲁菜','粤菜','江浙菜','家常小炒'],tags:['friends','budget','light']},
{name:'Brunch',e:'☕',sub:['贝果','三明治','松饼','可颂','咖啡简餐','早午餐拼盘'],tags:['light','treat']},
{name:'甜品',e:'🍰',sub:['奶茶','果茶','冰淇淋','蛋糕','糖水','芋圆'],tags:['treat','near']}
];
const MOODS=[{id:'random',e:'😊',name:'随便吃点'},{id:'spicy',e:'🌶️',name:'想吃辣'},{id:'light',e:'🍃',name:'清淡一点'},{id:'budget',e:'👛',name:'省点钱'},{id:'treat',e:'✨',name:'吃好一点'},{id:'tired',e:'😩',name:'今天好累'},{id:'friends',e:'👯',name:'和朋友'},{id:'near',e:'🚶',name:'不想走远'}];
const EXCLUDES=[{id:'hotpot',name:'不要火锅'},{id:'spicy',name:'不要太辣'},{id:'fast',name:'不要快餐'},{id:'dessert',name:'不要甜品'}];
const titles={home:'今天吃什么？',roll:'摇一摇',checkin:'吃饭打卡',records:'我的记录',favorites:'餐厅收藏',stats:'统计分析'};
let state={moods:new Set(['random']),excludes:new Set(),currentCat:null,currentSub:'',rating:5,photos:[]};
const DBKEY='eat_with_me_v9';
function loadData(){try{return JSON.parse(localStorage.getItem(DBKEY))||{checkins:[]}}catch{return{checkins:[]}}}
function saveData(d){localStorage.setItem(DBKEY,JSON.stringify(d))}
let data=loadData();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),1800)}
async function loadBoy(){try{const b=await fetch('./assets/boy.b64').then(r=>r.text());$$('[data-boy]').forEach(img=>img.src='data:image/webp;base64,'+b.trim())}catch(e){console.warn('boy asset failed',e)}}
function go(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+view));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#viewTitle').textContent=titles[view]||'饭搭子';window.scrollTo({top:0,behavior:'smooth'});if(view==='records')renderRecords();if(view==='favorites')renderFavorites();if(view==='stats')renderStats();}
$$('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function renderHomeMoods(){const box=$('#homeMoods');box.innerHTML='';MOODS.slice(0,4).forEach(m=>{const b=document.createElement('button');b.className='home-mood'+(state.moods.has(m.id)?' active':'');b.innerHTML=`<b>${m.e}</b><span>${m.name}</span>`;b.onclick=()=>{state.moods=new Set([m.id]);renderHomeMoods();renderAllMoods();$('#waiterBubble').textContent=m.id==='random'?'今天交给命运吧，我替你拍板。':`好，今天按「${m.name}」来。`;};box.appendChild(b)})}
function renderAllMoods(){const box=$('#allMoods');box.innerHTML='';MOODS.forEach(m=>{const b=document.createElement('button');b.className='mood-chip'+(state.moods.has(m.id)?' active':'');b.innerHTML=`<span>${m.e}</span><span>${m.name}</span>`;b.onclick=()=>{if(m.id==='random'){state.moods=new Set(['random'])}else{state.moods.delete('random');state.moods.has(m.id)?state.moods.delete(m.id):state.moods.add(m.id);if(!state.moods.size)state.moods.add('random')}renderAllMoods();renderHomeMoods()};box.appendChild(b)})}
function renderExcludes(){const box=$('#excludes');box.innerHTML='';EXCLUDES.forEach(x=>{const b=document.createElement('button');b.className='exclude'+(state.excludes.has(x.id)?' active':'');b.textContent='⊕ '+x.name;b.onclick=()=>{state.excludes.has(x.id)?state.excludes.delete(x.id):state.excludes.add(x.id);renderExcludes()};box.appendChild(b)})}
function candidatePool(){let pool=CATS.filter(c=>{if(state.excludes.has('hotpot')&&c.name==='火锅')return false;if(state.excludes.has('spicy')&&c.tags.includes('spicy'))return false;if(state.excludes.has('fast')&&c.name==='汉堡快餐')return false;if(state.excludes.has('dessert')&&c.name==='甜品')return false;return true});const moods=[...state.moods].filter(x=>x!=='random');if(moods.length){const p=pool.filter(c=>moods.some(m=>c.tags.includes(m)));if(p.length)pool=p}return pool.length?pool:CATS}
function randomCat(cat=null){state.currentCat=cat||candidatePool()[Math.floor(Math.random()*candidatePool().length)];state.currentSub='';updateRollResult();renderSavedRestaurants();}
function updateRollResult(){const c=state.currentCat;if(!c){$('#rollEmoji').textContent='🎲';$('#rollName').textContent='准备好了吗？';$('#rollDesc').textContent='点击下面，让今天少纠结一次。';return}$('#rollEmoji').textContent=c.e;$('#rollName').textContent=state.currentSub||c.name;$('#rollDesc').textContent=state.currentSub?`属于 ${c.name} · 今天就往这个方向找。`:`先定菜系：${c.name}。还可以继续摇具体一点。`;$('#rollWaiterText').textContent=state.currentSub?`“${state.currentSub}，我觉得今天很合适。不要再开第五个 App 了。”`:`“${c.name} 已经替你选好啦。要不要让我继续挑具体的？”`}
function detailRoll(){if(!state.currentCat)randomCat();state.currentSub=state.currentCat.sub[Math.floor(Math.random()*state.currentCat.sub.length)];updateRollResult()}
function acceptCurrent(){if(!state.currentCat)randomCat();const rec=state.currentSub?`${state.currentCat.name} · ${state.currentSub}`:state.currentCat.name;$('#recInput').value=rec;$('#actualInput').value=state.currentSub||state.currentCat.name;go('checkin');toast('已经帮你把推荐填进打卡表啦 ✨')}
$('#homeRoll').onclick=()=>{go('roll');setTimeout(()=>randomCat(),160)};$('#reroll').onclick=()=>randomCat();$('#detailRoll').onclick=detailRoll;$('#acceptRoll').onclick=acceptCurrent;$('#resetFilters').onclick=()=>{state.moods=new Set(['random']);state.excludes.clear();renderAllMoods();renderHomeMoods();renderExcludes();updateRollResult()};
function renderQuickCats(){const box=$('#quickCats');box.innerHTML='';CATS.slice(0,8).forEach(c=>{const b=document.createElement('button');b.className='quick-cat';b.innerHTML=`<b>${c.e}</b><span>${c.name}</span>`;b.onclick=()=>{go('roll');state.currentCat=c;state.currentSub='';updateRollResult();renderSavedRestaurants()};box.appendChild(b)})}
function renderCatGrid(){const box=$('#catGrid');box.innerHTML='';CATS.forEach(c=>{const el=document.createElement('div');el.className='cat-card';el.innerHTML=`<div><div class="cat-top"><span class="cat-emoji">${c.e}</span><span class="tag">${c.sub.length} 个细分</span></div><h3>${c.name}</h3><p>${c.sub.slice(0,4).join(' · ')}</p></div><button>从这里开始摇</button>`;el.querySelector('button').onclick=()=>{state.currentCat=c;state.currentSub='';updateRollResult();renderSavedRestaurants();window.scrollTo({top:0,behavior:'smooth'})};box.appendChild(el)})}
function renderSavedRestaurants(){const c=state.currentCat;const box=$('#savedRests');if(!c){box.innerHTML='<div class="saved-rest"><b>还没摇菜系</b><small>先摇一次，我再看你有没有吃过类似的店。</small></div>';$('#savedSuggestion').textContent='你收藏或吃过的餐厅会在这里优先出现；没有历史记录时不会瞎编真实店名。';return}const matches=data.checkins.filter(x=>x.restaurant&&((x.recommendation||'').includes(c.name)||(x.actual||'').includes(c.name))).slice(0,3);box.innerHTML='';if(!matches.length){box.innerHTML=`<div class="saved-rest"><b>还没有 ${c.name} 的个人餐厅记录</b><small>吃完回来打卡，以后这里就能直接提醒你。</small></div>`;$('#savedSuggestion').textContent=`你还没有记录过 ${c.name} 餐厅。第一版不虚构真实店铺，等积累记录后会优先推荐你收藏过的店。`;return}matches.forEach(x=>{const d=document.createElement('div');d.className='saved-rest';d.innerHTML=`<b>❤️ ${esc(x.restaurant)}</b><small>${x.actual?esc(x.actual):esc(x.recommendation)} · ${x.rating||5}★ ${x.price?'· ¥'+x.price+'/人':''}</small>`;box.appendChild(d)});$('#savedSuggestion').textContent=`找到了你以前吃过的 ${c.name}：优先从自己的真实记录里挑，比虚构店名靠谱。`}
function renderHomeRecent(){const box=$('#homeRecent');const items=data.checkins.slice(0,3);box.innerHTML='';if(!items.length){box.innerHTML='<div class="recent-item"><div class="recent-thumb">🍽️</div><div><b>还没有打卡</b><small>第一次吃完回来记一下吧</small></div><span class="mini-score">—</span></div>'}else items.forEach(x=>{const row=document.createElement('div');row.className='recent-item';const th=document.createElement(x.photos&&x.photos[0]?'img':'div');th.className='recent-thumb';if(x.photos&&x.photos[0])th.src=x.photos[0];else th.textContent='🍽️';const mid=document.createElement('div');mid.innerHTML=`<b>${esc(x.actual||x.recommendation||'一顿饭')}</b><small>${esc(x.restaurant||'未记录餐厅')} · ${new Date(x.createdAt).toLocaleDateString('zh-CN')}</small>`;const sc=document.createElement('span');sc.className='mini-score';sc.textContent=(x.rating||5)+'★';row.append(th,mid,sc);box.appendChild(row)});const count=data.checkins.length,priced=data.checkins.filter(x=>x.price>0),avg=priced.length?Math.round(priced.reduce((s,x)=>s+x.price,0)/priced.length):0,favs=new Set(data.checkins.filter(x=>x.favorite&&x.restaurant).map(x=>x.restaurant)).size;$('#homeStats').innerHTML=`<div class="mini-stat"><b>${count}</b><span>累计打卡</span></div><div class="mini-stat"><b>${favs}</b><span>收藏餐厅</span></div><div class="mini-stat"><b>${avg?'¥'+avg:'—'}</b><span>平均人均</span></div>`}
function renderStars(){const box=$('#stars');box.innerHTML='';for(let i=1;i<=5;i++){const b=document.createElement('button');b.textContent='★';b.className=i<=state.rating?'on':'';b.onclick=()=>{state.rating=i;renderStars()};box.appendChild(b)}}
async function resizeImage(file){const img=await createImageBitmap(file);const max=900,scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.78)}
$('#photoBtn').onclick=()=>$('#photoInput').click();$('#photoInput').onchange=async e=>{state.photos=[];for(const f of [...e.target.files].slice(0,4))state.photos.push(await resizeImage(f));$('#photoPreview').innerHTML=state.photos.map(s=>`<img src="${s}" alt="预览">`).join('')};
$('#saveCheckin').onclick=()=>{const actual=$('#actualInput').value.trim();if(!actual){toast('先告诉我这顿实际吃了什么～');return}const item={id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(),createdAt:Date.now(),recommendation:$('#recInput').value.trim(),actual,restaurant:$('#restaurantInput').value.trim(),price:Number($('#priceInput').value)||0,rating:state.rating,mood:$('#moodInput').value,comment:$('#commentInput').value.trim(),favorite:$('#favInput').checked,photos:[...state.photos]};data.checkins.unshift(item);saveData(data);['recInput','actualInput','restaurantInput','priceInput','commentInput'].forEach(id=>$('#'+id).value='');$('#favInput').checked=false;$('#photoInput').value='';$('#photoPreview').innerHTML='';state.photos=[];state.rating=5;renderStars();renderHomeRecent();toast('这顿已经收进你的吃饭档案 ✨');go('records')};
function renderRecords(){const box=$('#recordGrid');box.innerHTML='';if(!data.checkins.length){box.innerHTML='<div class="empty-state" style="grid-column:1/-1">还没有吃饭记录。先去摇一次，吃完回来打卡吧 🍚</div>';return}data.checkins.forEach(x=>{const el=document.createElement('article');el.className='record card';const photo=x.photos&&x.photos[0]?`<img src="${x.photos[0]}" alt="${esc(x.actual)}">`:'🍽️';el.innerHTML=`<div class="record-photo">${photo}</div><h3>${esc(x.actual||x.recommendation||'一顿饭')}</h3><small>${esc(x.restaurant||'未记录餐厅')} · ${new Date(x.createdAt).toLocaleDateString('zh-CN')} · ${x.rating||5}★</small>${x.comment?`<p>${esc(x.comment)}</p>`:''}<div class="record-bottom"><span class="tag">${esc(x.recommendation||x.mood||'自由发挥')}</span><button class="heart-btn">${x.favorite?'❤️':'♡'}</button></div>`;el.querySelector('.heart-btn').onclick=()=>{x.favorite=!x.favorite;saveData(data);renderRecords();renderFavorites();renderHomeRecent()};box.appendChild(el)})}
function renderFavorites(){const box=$('#favGrid');const map=new Map();data.checkins.filter(x=>x.favorite&&x.restaurant).forEach(x=>{if(!map.has(x.restaurant))map.set(x.restaurant,x)});const arr=[...map.values()];box.innerHTML='';if(!arr.length){box.innerHTML='<div class="empty-state" style="grid-column:1/-1">还没有收藏餐厅。打卡时勾选“收藏这家餐厅”，这里就会出现。</div>';return}arr.forEach(x=>{const el=document.createElement('div');el.className='fav-card card';el.innerHTML=`<div class="fav-icon">❤️</div><div><b>${esc(x.restaurant)}</b><small>${esc(x.actual||x.recommendation)} · ${x.rating||5}★ ${x.price?'· ¥'+x.price+'/人':''}</small></div><button>取消收藏</button>`;el.querySelector('button').onclick=()=>{data.checkins.filter(y=>y.restaurant===x.restaurant).forEach(y=>y.favorite=false);saveData(data);renderFavorites();renderHomeRecent()};box.appendChild(el)})}
function renderStats(){const n=data.checkins.length,priced=data.checkins.filter(x=>x.price>0),avg=priced.length?Math.round(priced.reduce((s,x)=>s+x.price,0)/priced.length):0,rating=n?(data.checkins.reduce((s,x)=>s+(x.rating||0),0)/n).toFixed(1):'—',favs=new Set(data.checkins.filter(x=>x.favorite&&x.restaurant).map(x=>x.restaurant)).size;$('#statGrid').innerHTML=`<div class="stat-card card"><b>${n}</b><span>累计打卡</span></div><div class="stat-card card"><b>${favs}</b><span>收藏餐厅</span></div><div class="stat-card card"><b>${avg?'¥'+avg:'—'}</b><span>平均人均</span></div><div class="stat-card card"><b>${rating}</b><span>平均评分</span></div>`;const freq={};data.checkins.forEach(x=>{const key=(x.recommendation||x.actual||'其他').split('·')[0].trim();freq[key]=(freq[key]||0)+1});const rows=Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,7),max=Math.max(1,...rows.map(x=>x[1]));$('#catBars').innerHTML=rows.length?rows.map(([k,v])=>`<div class="bar-row"><span>${esc(k)}</span><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div><b>${v}</b></div>`).join(''):'<div class="empty-state">打卡几次后，这里会出现你的菜系偏好。</div>';const photos=data.checkins.flatMap(x=>x.photos||[]).slice(0,12);$('#photoWall').innerHTML=photos.length?photos.map(p=>`<div><img src="${p}" alt="美食照片"></div>`).join(''):'<div>📷</div><div>🍜</div><div>🍣</div><div>🍲</div>'}
$('#shareBtn').onclick=async()=>{const txt=state.currentCat?`今天饭搭子帮我选了：${state.currentSub||state.currentCat.name} 🍚`:'我在用「饭搭子」决定今天吃什么 🍚';try{if(navigator.share)await navigator.share({title:'今天吃什么？',text:txt,url:location.href});else{await navigator.clipboard.writeText(txt+' '+location.href);toast('分享文字和网址已复制')}}catch(e){}}
function init(){renderHomeMoods();renderAllMoods();renderExcludes();renderQuickCats();renderCatGrid();renderHomeRecent();renderStars();renderSavedRestaurants();loadBoy();}
init();